In [20]:
import numpy as np

In [21]:
import pandas as pd

In [22]:
dataset = pd.read_csv("Social_Network_Ads.csv")

In [23]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [24]:
dataset = pd.get_dummies(dataset, dtype=int, drop_first=True)

In [25]:
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [26]:
dataset = dataset.drop("User ID", axis=1)

In [27]:
dataset

     Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [28]:
dataset.columns

Index(['Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [29]:
independent = dataset[["Age", "EstimatedSalary", "Gender_Male"]]

In [30]:
independent

     Age  EstimatedSalary  Gender_Male
0     19            19000            1
1     35            20000            1
2     26            43000            0
3     27            57000            0
4     19            76000            1
..   ...              ...          ...
395   46            41000            0
396   51            23000            1
397   50            20000            0
398   36            33000            1
399   49            36000            0

[400 rows x 3 columns]

In [31]:
dependent = dataset[["Purchased"]]

In [32]:
dependent

     Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [33]:
#Training set and Testing set split

In [34]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(independent,dependent, test_size =0.30, random_state =0)

In [35]:
#Model Creation Naive Bayes Classification | Evaluation Metrics
#from sklearn.naive_bayes import MultinomialNB
#Classifier = MultinomialNB()
#Classifier.fit(x_train, y_train)
#y_pred=Classifier.predict(x_test)
#from sklearn.metrics import confusion_matrix
#cm = confusion_matrix(y_test, y_pred)
#print(cm)
#from sklearn.metrics import classification_report
#clf_report = classification_report(y_test, y_pred)
#print(clf_report)

In [36]:
#Model Creation Naive Bayes Classification | Evaluation Metrics
#from sklearn.naive_bayes import GuassianNB
#Classifier = GuassianNB()
#Classifier.fit(x_train, y_train)
#y_pred=Classifier.predict(x_test)
#from sklearn.metrics import confusion_matrix
#cm = confusion_matrix(y_test, y_pred)
#print(cm)
#from sklearn.metrics import classification_report
#clf_report = classification_report(y_test, y_pred)
#print(clf_report)

In [37]:
#Model Creation BernoulliNB Classification | Evaluation Metrics
#from sklearn.naive_bayes import BernoulliNB
#Classifier = BernoulliNB()
#Classifier.fit(x_train, y_train)
#y_pred = Classifier.predict(x_test)
#from sklearn.metrics import confusion_matrix
#cm = confusion_matrix(y_test, y_pred)
#print(cm)
#from sklearn.metrics import classification_report
#clf_report = classification_report(y_test, y_pred)
#print(clf_report)

In [38]:
#Model Creation CategoricalNB Classification | Evaluation Metrics
from sklearn.naive_bayes import CategoricalNB
Classifier = CategoricalNB()
Classifier.fit(x_train, np.ravel(y_train))
y_pred = Classifier.predict(x_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)
print(clf_report)

[[76  3]
 [ 9 32]]
              precision    recall  f1-score   support

           0       0.89      0.96      0.93        79
           1       0.91      0.78      0.84        41

    accuracy                           0.90       120
   macro avg       0.90      0.87      0.88       120
weighted avg       0.90      0.90      0.90       120

In [39]:
#Model Creation ComplementNB Classification | Evaluation Metrics
#from sklearn.naive_bayes import ComplementNB
#Classifier = ComplementNB()
#Classifier.fit(x_train, y_train)
#y_pred = Classifier.predict(x_test)
#from sklearn.metrics import confusion_matrix
#cm = confusion_matrix(y_test, y_pred)
#print(cm)
#from sklearn.metrics import classification_report
#clf_report = classification_report(y_test, y_pred)
#print(clf_report)