In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("Social_Network_Ads.csv")

In [3]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
dataset = pd.get_dummies(dataset, dtype=int, drop_first = True)

In [5]:
#Converting categorical data to numerical data and removing redundant column

In [6]:
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [7]:
dataset.columns

Index(['User ID', 'Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [8]:
independent = dataset[['User ID', 'Age', 'EstimatedSalary', 
       'Gender_Male']]

In [9]:
independent

      User ID  Age  EstimatedSalary  Gender_Male
0    15624510   19            19000            1
1    15810944   35            20000            1
2    15668575   26            43000            0
3    15603246   27            57000            0
4    15804002   19            76000            1
..        ...  ...              ...          ...
395  15691863   46            41000            0
396  15706071   51            23000            1
397  15654296   50            20000            0
398  15755018   36            33000            1
399  15594041   49            36000            0

[400 rows x 4 columns]

In [10]:
dependent = dataset[["Purchased"]]

In [11]:
dependent

     Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train, x_test, y_train, y_test = train_test_split(independent, dependent, test_size=0.30, random_state=0)

In [14]:
#Splitting training dataset and test dataset above

In [15]:
x_train

      User ID  Age  EstimatedSalary  Gender_Male
92   15809823   26            15000            1
223  15593715   60           102000            1
234  15619407   38           112000            0
232  15813113   40           107000            1
377  15800215   42            53000            0
..        ...  ...              ...          ...
323  15619465   48            30000            0
192  15779581   29            43000            1
117  15591433   36            52000            1
47   15776348   27            54000            0
172  15794661   26           118000            0

[280 rows x 4 columns]

In [16]:
#Using Standardisation technique to find the best model; x_train above - before standardisation

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
sc=StandardScaler()

In [19]:
x_train=sc.fit_transform(x_train)

In [20]:
x_test = sc.transform(x_test)

In [21]:
#x_train

In [22]:
#x_Train after standardisation technique above

In [23]:
from sklearn.svm import SVC

In [24]:
Classifier = SVC(kernel ='rbf',random_state = 0)

In [25]:
Classifier.fit(x_train, y_train)

C:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVC(random_state=0)

In [26]:
#Classifier.intercept_

In [27]:
#Viewing the origin or intercept

In [28]:
#Classifier.n_support_

In [29]:
#Viewing the number of support vectors used

In [30]:
#Classifier.support_

In [31]:
#Viewing the support vectors

In [32]:
y_pred=Classifier.predict(x_test)

In [33]:
#Evaluation Metrics for Support vector Classification

In [34]:
from sklearn.metrics import confusion_matrix

In [35]:
cm= confusion_matrix(y_test, y_pred)

In [36]:
cm

array([[73,  6],
       [ 5, 36]])

In [37]:
from sklearn.metrics import classification_report

In [38]:
clf_report = classification_report(y_test, y_pred)

In [39]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.94      0.92      0.93        79
           1       0.86      0.88      0.87        41

    accuracy                           0.91       120
   macro avg       0.90      0.90      0.90       120
weighted avg       0.91      0.91      0.91       120