In [35]:
import pandas as pd

In [36]:
dataset = pd.read_csv("Social_Network_Ads.csv")

In [37]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [38]:
dataset = pd.get_dummies(dataset, dtype=int, drop_first=True)

In [39]:
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [40]:
dataset.columns

Index(['User ID', 'Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [41]:
independent = dataset[['User ID', 'Age', 'EstimatedSalary', 'Gender_Male']]

In [42]:
independent

      User ID  Age  EstimatedSalary  Gender_Male
0    15624510   19            19000            1
1    15810944   35            20000            1
2    15668575   26            43000            0
3    15603246   27            57000            0
4    15804002   19            76000            1
..        ...  ...              ...          ...
395  15691863   46            41000            0
396  15706071   51            23000            1
397  15654296   50            20000            0
398  15755018   36            33000            1
399  15594041   49            36000            0

[400 rows x 4 columns]

In [43]:
dependent = dataset[['Purchased']]

In [44]:
dependent

     Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
x_train,x_test,y_train,y_test = train_test_split(independent,dependent,test_size=0.30, random_state=0)

In [47]:
x_train

      User ID  Age  EstimatedSalary  Gender_Male
92   15809823   26            15000            1
223  15593715   60           102000            1
234  15619407   38           112000            0
232  15813113   40           107000            1
377  15800215   42            53000            0
..        ...  ...              ...          ...
323  15619465   48            30000            0
192  15779581   29            43000            1
117  15591433   36            52000            1
47   15776348   27            54000            0
172  15794661   26           118000            0

[280 rows x 4 columns]

In [48]:
x_test

      User ID  Age  EstimatedSalary  Gender_Male
132  15725660   30            87000            1
309  15652400   38            50000            0
341  15776844   35            75000            1
196  15738448   30            79000            0
246  15638003   35            50000            0
..        ...  ...              ...          ...
216  15636023   49            65000            1
259  15815236   45           131000            0
49   15793813   31            89000            0
238  15617877   46            82000            0
343  15629739   47            51000            0

[120 rows x 4 columns]

In [49]:
y_train

     Purchased
92           0
223          1
234          0
232          1
377          0
..         ...
323          1
192          0
117          0
47           0
172          0

[280 rows x 1 columns]

In [50]:
y_test

     Purchased
132          0
309          0
341          0
196          0
246          0
..         ...
216          0
259          1
49           0
238          0
343          1

[120 rows x 1 columns]

In [51]:
#Model creation in RandomForest Classification

In [52]:
from sklearn.ensemble import RandomForestClassifier

In [53]:
Classifier=RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=0)

In [54]:
Classifier.fit(x_train,y_train)

C:\Anaconda\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [55]:
y_pred=Classifier.predict(x_test)

In [56]:
#Evaluation Metrics for Classification

In [57]:
from sklearn.metrics import confusion_matrix

In [58]:
cm = confusion_matrix(y_test,y_pred)

In [59]:
print(cm)

[[73  6]
 [ 4 37]]

In [60]:
#Finding the best model - we use classification report

In [61]:
#import pickle

In [62]:
from sklearn.metrics import classification_report

In [63]:
clf_report = classification_report(y_test, y_pred)

In [64]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.95      0.92      0.94        79
           1       0.86      0.90      0.88        41

    accuracy                           0.92       120
   macro avg       0.90      0.91      0.91       120
weighted avg       0.92      0.92      0.92       120